### ISSUE TITLE
Feature Request: Migration/Synchronisation of Issues in Redmine

### ISSUE THREAD

**Issue by timoc** [taigaio/redmine-migrator#5]
Hi,

I still need to use Redmine because it is managing my git repositories, and has tight integration between my issues and the code checked in for those issues. As far as i can tell, Taigaio cannot do this, or at least it does not manage git repositories. 

But i would like to use taigaio for kanban etc too. So, can you adjust the tool to give 'tighter' integration with redmine, that is, there is a link between the redmine issue and taigaio issues, such that changes in one are reflected in the other?

**Comment by ilopmar** [comment]
Hi Tim.

Thank you for your request. I'm afraid that's not possible at the moment. Please keep in mind that this is a tool to migrate all the data from Redmine to Taiga and don't use Redmine again after the migration. We don't planned it to keep both systems synchronized.

Regards, Iván.
